<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Armor.Core\Armor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
  </ItemGroup>

</Project>
